# This file was generated by GoReleaser. DO NOT EDIT.
class GitGet < Formula
  desc "Clone git repositories into namespaced directories like go get."
  homepage "https://github.com/yi-jiayu/git-get"
  url "https://github.com/yi-jiayu/git-get/releases/download/v0.1.0/git-get_0.1.0_Darwin_x86_64.tar.gz"
  version "0.1.0"
  sha256 "0e30978ec48d8ef3729a84810c583ef1f8d7448e24f9059e927ab109ef9f175a"

  def install
    bin.install "git-get"
  end
end
