# This file was generated by GoReleaser. DO NOT EDIT.
class GitGet < Formula
  desc "Clone git repositories into namespaced directories like go get."
  homepage "https://github.com/yi-jiayu/git-get"
  url "https://github.com/yi-jiayu/git-get/releases/download/v0.3.3/git-get_0.3.3_darwin_amd64.tar.gz"
  version "0.3.3"
  sha256 "c3fb8e2a8ae3230ec3b82e55fdd413af5f18ba9789752fbe85c20afab5a8f8a0"

  def install
    bin.install "git-get"
    man1.install "git-get.1"
  end
end
